// Generated by scripts (favicon/brand pass) - intrinsic pixel sizes of the logo PNGs, so next/image can size them without layout shift.
export const BRAND_DIMS: Record<string, [number, number]> = {"/brand/apple-touch-icon.png":[180,180],"/brand/favicon-192.png":[192,192],"/brand/favicon-32.png":[32,32],"/brand/logo-emblem-dark.png":[795,790],"/brand/logo-emblem.png":[795,790],"/brand/logo-horizontal-dark.png":[1767,494],"/brand/logo-horizontal.png":[1767,460],"/brand/logo-stacked-dark.png":[1299,1049],"/brand/logo-stacked.png":[1299,1049],"/brand/logo2-emblem-dark.png":[903,950],"/brand/logo2-emblem.png":[903,950],"/brand/logo2-horizontal-dark.png":[1561,427],"/brand/logo2-horizontal.png":[1561,427],"/brand/logo2-stacked-dark.png":[1543,1392],"/brand/logo3-emblem-dark.png":[673,712],"/brand/logo3-emblem-white.png":[673,712],"/brand/logo3-horizontal-dark.png":[2056,712],"/brand/logo3-horizontal.png":[2056,712],"/brand/logo4-horizontal-dark.png":[1164,276],"/brand/logo4-horizontal.png":[1164,276],"/brand/logo5-horizontal-dark.png":[1176,288],"/brand/logo5-horizontal.png":[1176,288],"/brand/logo6-horizontal-dark.png":[1179,240],"/brand/logo6-horizontal.png":[1179,240]};
/** width/height for a logo rendered at a given CSS height; the ?v= cache-buster on src is ignored. */
export const logoSize = (src: string, h: number): { width: number; height: number } => {
  const d = BRAND_DIMS[src.split("?")[0]];
  return d ? { width: Math.round((h * d[0]) / d[1]), height: h } : { width: Math.round(h * 3.6), height: h };
};
/** CSS aspect-ratio matching logoSize's rounded width/height attributes. The optimizer resizes to a slightly different ratio, so
 * without this the rendered width can land 1px off the attribute and next/image logs a dev warning. */
export const logoRatio = (src: string, h: number): { aspectRatio: string } => {
  const s = logoSize(src, h);
  return { aspectRatio: s.width + " / " + s.height };
};
